# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/app_queries.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/app_queries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.app import app_pb2 as truffle_dot_app_dot_app__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/os/app_queries.proto\x12\ntruffle.os\x1a\x15truffle/app/app.proto\"\x13\n\x11GetAllAppsRequest\"4\n\x12GetAllAppsResponse\x12\x1e\n\x04\x61pps\x18\x01 \x03(\x0b\x32\x10.truffle.app.App\"$\n\x10\x44\x65leteAppRequest\x12\x10\n\x08\x61pp_uuid\x18\x01 \x01(\t\"\x13\n\x11\x44\x65leteAppResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.app_queries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLAPPSREQUEST']._serialized_start=67
  _globals['_GETALLAPPSREQUEST']._serialized_end=86
  _globals['_GETALLAPPSRESPONSE']._serialized_start=88
  _globals['_GETALLAPPSRESPONSE']._serialized_end=140
  _globals['_DELETEAPPREQUEST']._serialized_start=142
  _globals['_DELETEAPPREQUEST']._serialized_end=178
  _globals['_DELETEAPPRESPONSE']._serialized_start=180
  _globals['_DELETEAPPRESPONSE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
