# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/background_feed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/background_feed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from truffle.common import content_pb2 as truffle_dot_common_dot_content__pb2
from truffle.os import proactivity_pb2 as truffle_dot_os_dot_proactivity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n truffle/os/background_feed.proto\x12\ntruffle.os\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1ctruffle/common/content.proto\x1a\x1ctruffle/os/proactivity.proto\"\xdc\x01\n\x08\x46\x65\x65\x64\x43\x61rd\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x32\n\rmedia_sources\x18\x03 \x03(\x0b\x32\x1b.truffle.common.MediaSource\x12\x12\n\nsource_uri\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x88\x01\x01\x42\x0b\n\t_metadata\"8\n\x0e\x42\x61\x63kgroundFeed\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.truffle.os.FeedEntry\"\xce\x01\n\x15\x46\x65\x65\x64\x45ntryNotification\x12\x11\n\tentry_ids\x18\x01 \x03(\x04\x12>\n\toperation\x18\x02 \x01(\x0e\x32+.truffle.os.FeedEntryNotification.Operation\"b\n\tOperation\x12\x15\n\x11OPERATION_INVALID\x10\x00\x12\x11\n\rOPERATION_ADD\x10\x01\x12\x14\n\x10OPERATION_DELETE\x10\x02\x12\x15\n\x11OPERATION_REFRESH\x10\x03\"\xb0\x01\n\tFeedEntry\x12\n\n\x02id\x18\x01 \x01(\x04\x12$\n\x04\x63\x61rd\x18\x02 \x01(\x0b\x32\x14.truffle.os.FeedCardH\x00\x12\x37\n\x10proactive_action\x18\x03 \x01(\x0b\x32\x1b.truffle.os.ProactiveActionH\x00\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\t\n\x07\x63ontent\">\n\x14\x46\x65\x65\x64\x45ntryTaskContext\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.truffle.os.FeedEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.background_feed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDCARD']._serialized_start=172
  _globals['_FEEDCARD']._serialized_end=392
  _globals['_BACKGROUNDFEED']._serialized_start=394
  _globals['_BACKGROUNDFEED']._serialized_end=450
  _globals['_FEEDENTRYNOTIFICATION']._serialized_start=453
  _globals['_FEEDENTRYNOTIFICATION']._serialized_end=659
  _globals['_FEEDENTRYNOTIFICATION_OPERATION']._serialized_start=561
  _globals['_FEEDENTRYNOTIFICATION_OPERATION']._serialized_end=659
  _globals['_FEEDENTRY']._serialized_start=662
  _globals['_FEEDENTRY']._serialized_end=838
  _globals['_FEEDENTRYTASKCONTEXT']._serialized_start=840
  _globals['_FEEDENTRYTASKCONTEXT']._serialized_end=902
# @@protoc_insertion_point(module_scope)
