# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/background_feed_queries.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/background_feed_queries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.app import background_pb2 as truffle_dot_app_dot_background__pb2
from truffle.os import background_feed_pb2 as truffle_dot_os_dot_background__feed__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(truffle/os/background_feed_queries.proto\x12\ntruffle.os\x1a\x1ctruffle/app/background.proto\x1a truffle/os/background_feed.proto\"\x8a\x01\n\x18GetBackgroundFeedRequest\x12\x17\n\x0ftarget_entry_id\x18\x01 \x01(\x04\x12\x12\n\nmax_before\x18\x02 \x01(\x05\x12\x11\n\tmax_after\x18\x03 \x01(\x05\x12\x17\n\x0finclude_actions\x18\x04 \x01(\x08\x12\x15\n\rinclude_cards\x18\x05 \x01(\x08\"C\n\x19GetBackgroundFeedResponse\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.truffle.os.FeedEntry\"\x1d\n\x1bGetLatestFeedEntryIDRequest\"<\n\x1cGetLatestFeedEntryIDResponse\x12\x1c\n\x14latest_feed_entry_id\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.background_feed_queries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBACKGROUNDFEEDREQUEST']._serialized_start=121
  _globals['_GETBACKGROUNDFEEDREQUEST']._serialized_end=259
  _globals['_GETBACKGROUNDFEEDRESPONSE']._serialized_start=261
  _globals['_GETBACKGROUNDFEEDRESPONSE']._serialized_end=328
  _globals['_GETLATESTFEEDENTRYIDREQUEST']._serialized_start=330
  _globals['_GETLATESTFEEDENTRYIDREQUEST']._serialized_end=359
  _globals['_GETLATESTFEEDENTRYIDRESPONSE']._serialized_start=361
  _globals['_GETLATESTFEEDENTRYIDRESPONSE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
