# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/client_user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/client_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.os import client_metadata_pb2 as truffle_dot_os_dot_client__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/os/client_user.proto\x12\ntruffle.os\x1a truffle/os/client_metadata.proto\"\x8c\x01\n\x16RegisterNewUserRequest\x12,\n\x08metadata\x18\x01 \x01(\x0b\x32\x1a.truffle.os.ClientMetadata\x12\x14\n\x07user_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08password\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_user_idB\x0b\n\t_password\"9\n\x17RegisterNewUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"&\n\x15UserIDForTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"M\n\x16UserIDForTokenResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\x08username\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_username\"-\n\x19SetNewUserPasswordRequest\x12\x10\n\x08password\x18\x01 \x01(\t\"\x1c\n\x1aSetNewUserPasswordResponse\"+\n\x17SetLoginUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1a\n\x18SetLoginUsernameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.client_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERNEWUSERREQUEST']._serialized_start=79
  _globals['_REGISTERNEWUSERREQUEST']._serialized_end=219
  _globals['_REGISTERNEWUSERRESPONSE']._serialized_start=221
  _globals['_REGISTERNEWUSERRESPONSE']._serialized_end=278
  _globals['_USERIDFORTOKENREQUEST']._serialized_start=280
  _globals['_USERIDFORTOKENREQUEST']._serialized_end=318
  _globals['_USERIDFORTOKENRESPONSE']._serialized_start=320
  _globals['_USERIDFORTOKENRESPONSE']._serialized_end=397
  _globals['_SETNEWUSERPASSWORDREQUEST']._serialized_start=399
  _globals['_SETNEWUSERPASSWORDREQUEST']._serialized_end=444
  _globals['_SETNEWUSERPASSWORDRESPONSE']._serialized_start=446
  _globals['_SETNEWUSERPASSWORDRESPONSE']._serialized_end=474
  _globals['_SETLOGINUSERNAMEREQUEST']._serialized_start=476
  _globals['_SETLOGINUSERNAMEREQUEST']._serialized_end=519
  _globals['_SETLOGINUSERNAMERESPONSE']._serialized_start=521
  _globals['_SETLOGINUSERNAMERESPONSE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
