# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/client_remote.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/client_remote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.os import client_metadata_pb2 as truffle_dot_os_dot_client__metadata__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etruffle/os/client_remote.proto\x12\ntruffle.os\x1a truffle/os/client_metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n\x11RemoteAccessToken\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0b\n\x03jwt\x18\x02 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1d\n\x15remote_access_address\x18\x04 \x01(\t\"\x1d\n\x1bNewRemoteAccessTokenRequest\"L\n\x1cNewRemoteAccessTokenResponse\x12,\n\x05token\x18\x01 \x01(\x0b\x32\x1d.truffle.os.RemoteAccessToken\"W\n\x12RemoteAccessStatus\x12\x11\n\tsupported\x18\x01 \x01(\x08\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x1d\n\x15remote_access_address\x18\x03 \x01(\t\"\x1e\n\x1cGetRemoteAccessStatusRequest\"O\n\x1dGetRemoteAccessStatusResponse\x12.\n\x06status\x18\x01 \x01(\x0b\x32\x1e.truffle.os.RemoteAccessStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.client_remote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOTEACCESSTOKEN']._serialized_start=114
  _globals['_REMOTEACCESSTOKEN']._serialized_end=244
  _globals['_NEWREMOTEACCESSTOKENREQUEST']._serialized_start=246
  _globals['_NEWREMOTEACCESSTOKENREQUEST']._serialized_end=275
  _globals['_NEWREMOTEACCESSTOKENRESPONSE']._serialized_start=277
  _globals['_NEWREMOTEACCESSTOKENRESPONSE']._serialized_end=353
  _globals['_REMOTEACCESSSTATUS']._serialized_start=355
  _globals['_REMOTEACCESSSTATUS']._serialized_end=442
  _globals['_GETREMOTEACCESSSTATUSREQUEST']._serialized_start=444
  _globals['_GETREMOTEACCESSSTATUSREQUEST']._serialized_end=474
  _globals['_GETREMOTEACCESSSTATUSRESPONSE']._serialized_start=476
  _globals['_GETREMOTEACCESSSTATUSRESPONSE']._serialized_end=555
# @@protoc_insertion_point(module_scope)
