# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/proactivity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/proactivity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/os/proactivity.proto\x12\ntruffle.os\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x04\n\x0fProactiveAction\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12:\n\nactionable\x18\x04 \x01(\x0b\x32&.truffle.os.ProactiveAction.Actionable\x12\x32\n\x06status\x18\x05 \x01(\x0e\x32\".truffle.os.ProactiveAction.Status\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tapp_uuids\x18\x08 \x03(\t\x12\x1b\n\x13prompt_for_subagent\x18\t \x01(\t\x1a\x9c\x01\n\nActionable\x12J\n\x0c\x62oolean_text\x18\x01 \x01(\x0b\x32\x32.truffle.os.ProactiveAction.Actionable.BooleanTextH\x00\x1a:\n\x0b\x42ooleanText\x12\x0f\n\x07\x61pprove\x18\x01 \x01(\x08\x12\x11\n\x04text\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_textB\x06\n\x04type\"\x92\x01\n\x06Status\x12\x18\n\x14\x41\x43TION_STATE_INVALID\x10\x00\x12\x18\n\x14\x41\x43TION_STATE_PENDING\x10\x01\x12\x1c\n\x18\x41\x43TION_STATE_IN_PROGRESS\x10\x02\x12\x1a\n\x16\x41\x43TION_STATE_CANCELLED\x10\x03\x12\x1a\n\x16\x41\x43TION_STATE_COMPLETED\x10\x04\"n\n\x1d\x41pproveProactiveActionRequest\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\x04\x12;\n\x0buser_action\x18\x02 \x01(\x0b\x32&.truffle.os.ProactiveAction.Actionable\"U\n\x1e\x41pproveProactiveActionResponse\x12\x33\n\x0eupdated_action\x18\x01 \x01(\x0b\x32\x1b.truffle.os.ProactiveAction\"0\n\x1c\x43\x61ncelProactiveActionRequest\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\x04\"\x1f\n\x1d\x43\x61ncelProactiveActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.proactivity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROACTIVEACTION']._serialized_start=78
  _globals['_PROACTIVEACTION']._serialized_end=695
  _globals['_PROACTIVEACTION_ACTIONABLE']._serialized_start=390
  _globals['_PROACTIVEACTION_ACTIONABLE']._serialized_end=546
  _globals['_PROACTIVEACTION_ACTIONABLE_BOOLEANTEXT']._serialized_start=480
  _globals['_PROACTIVEACTION_ACTIONABLE_BOOLEANTEXT']._serialized_end=538
  _globals['_PROACTIVEACTION_STATUS']._serialized_start=549
  _globals['_PROACTIVEACTION_STATUS']._serialized_end=695
  _globals['_APPROVEPROACTIVEACTIONREQUEST']._serialized_start=697
  _globals['_APPROVEPROACTIVEACTIONREQUEST']._serialized_end=807
  _globals['_APPROVEPROACTIVEACTIONRESPONSE']._serialized_start=809
  _globals['_APPROVEPROACTIVEACTIONRESPONSE']._serialized_end=894
  _globals['_CANCELPROACTIVEACTIONREQUEST']._serialized_start=896
  _globals['_CANCELPROACTIVEACTIONREQUEST']._serialized_end=944
  _globals['_CANCELPROACTIVEACTIONRESPONSE']._serialized_start=946
  _globals['_CANCELPROACTIVEACTIONRESPONSE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
