# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/system_actions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/system_actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftruffle/os/system_actions.proto\x12\ntruffle.os\"Q\n\x19SystemFactoryResetRequest\x12\x1e\n\x11\x63onfirmation_code\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_confirmation_code\"P\n\x1aSystemFactoryResetResponse\x12\x19\n\x11\x63onfirmation_code\x18\x01 \x01(\t\x12\x17\n\x0freset_initiated\x18\x02 \x01(\x08\"\"\n SystemClearOtherUsersDataRequest\">\n!SystemClearOtherUsersDataResponse\x12\x19\n\x11num_users_cleared\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.system_actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMFACTORYRESETREQUEST']._serialized_start=47
  _globals['_SYSTEMFACTORYRESETREQUEST']._serialized_end=128
  _globals['_SYSTEMFACTORYRESETRESPONSE']._serialized_start=130
  _globals['_SYSTEMFACTORYRESETRESPONSE']._serialized_end=210
  _globals['_SYSTEMCLEAROTHERUSERSDATAREQUEST']._serialized_start=212
  _globals['_SYSTEMCLEAROTHERUSERSDATAREQUEST']._serialized_end=246
  _globals['_SYSTEMCLEAROTHERUSERSDATARESPONSE']._serialized_start=248
  _globals['_SYSTEMCLEAROTHERUSERSDATARESPONSE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
