# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/system_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/system_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.os import hardware_settings_pb2 as truffle_dot_os_dot_hardware__settings__pb2
from truffle.os import dream_pb2 as truffle_dot_os_dot_dream__pb2

from truffle.os.hardware_settings_pb2 import *
from truffle.os.dream_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n truffle/os/system_settings.proto\x12\ntruffle.os\x1a\"truffle/os/hardware_settings.proto\x1a\x16truffle/os/dream.proto\"\xd6\x02\n\x0eSystemSettings\x12<\n\x11hardware_settings\x18\x01 \x01(\x0b\x32\x1c.truffle.os.HardwareSettingsH\x00\x88\x01\x01\x12\x34\n\rtask_settings\x18\x02 \x01(\x0b\x32\x18.truffle.os.TaskSettingsH\x01\x88\x01\x01\x12:\n\x10\x66\x65\x61ture_settings\x18\x03 \x01(\x0b\x32\x1b.truffle.os.FeatureSettingsH\x02\x88\x01\x01\x12?\n\x13\x64ream_mode_settings\x18\x04 \x01(\x0b\x32\x1d.truffle.os.DreamModeSettingsH\x03\x88\x01\x01\x42\x14\n\x12_hardware_settingsB\x10\n\x0e_task_settingsB\x13\n\x11_feature_settingsB\x16\n\x14_dream_mode_settings\"W\n\x0f\x46\x65\x61tureSettings\x12&\n\x19\x64isable_background_agents\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x1c\n\x1a_disable_background_agents\"\x0e\n\x0cTaskSettings\"9\n\x1bResetDefaultSettingsRequest\x12\x1a\n\x12reset_led_settings\x18\x01 \x01(\x08\"L\n\x1cResetDefaultSettingsResponse\x12,\n\x08settings\x18\x01 \x01(\x0b\x32\x1a.truffle.os.SystemSettingsP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.system_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSETTINGS']._serialized_start=109
  _globals['_SYSTEMSETTINGS']._serialized_end=451
  _globals['_FEATURESETTINGS']._serialized_start=453
  _globals['_FEATURESETTINGS']._serialized_end=540
  _globals['_TASKSETTINGS']._serialized_start=542
  _globals['_TASKSETTINGS']._serialized_end=556
  _globals['_RESETDEFAULTSETTINGSREQUEST']._serialized_start=558
  _globals['_RESETDEFAULTSETTINGSREQUEST']._serialized_end=615
  _globals['_RESETDEFAULTSETTINGSRESPONSE']._serialized_start=617
  _globals['_RESETDEFAULTSETTINGSRESPONSE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
