# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/system_mode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/system_mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/os/system_mode.proto\x12\ntruffle.os\x1a\x1egoogle/protobuf/duration.proto\"C\n\x1bRequestSystemModeSetRequest\x12$\n\x04mode\x18\x01 \x01(\x0e\x32\x16.truffle.os.SystemMode\"D\n\x1cRequestSystemModeSetResponse\x12$\n\x04mode\x18\x01 \x01(\x0e\x32\x16.truffle.os.SystemMode\"\x16\n\x14GetSystemModeRequest\"=\n\x15GetSystemModeResponse\x12$\n\x04mode\x18\x01 \x01(\x0e\x32\x16.truffle.os.SystemMode\"}\n\x1cSystemModeChangeNotification\x12(\n\x08new_mode\x18\x01 \x01(\x0e\x32\x16.truffle.os.SystemMode\x12+\n\x03\x65ta\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationH\x00\x88\x01\x01\x42\x06\n\x04_eta*?\n\nSystemMode\x12\x10\n\x0cMODE_INVALID\x10\x00\x12\x0f\n\x0bMODE_NORMAL\x10\x01\x12\x0e\n\nMODE_DREAM\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.system_mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMMODE']._serialized_start=429
  _globals['_SYSTEMMODE']._serialized_end=492
  _globals['_REQUESTSYSTEMMODESETREQUEST']._serialized_start=76
  _globals['_REQUESTSYSTEMMODESETREQUEST']._serialized_end=143
  _globals['_REQUESTSYSTEMMODESETRESPONSE']._serialized_start=145
  _globals['_REQUESTSYSTEMMODESETRESPONSE']._serialized_end=213
  _globals['_GETSYSTEMMODEREQUEST']._serialized_start=215
  _globals['_GETSYSTEMMODEREQUEST']._serialized_end=237
  _globals['_GETSYSTEMMODERESPONSE']._serialized_start=239
  _globals['_GETSYSTEMMODERESPONSE']._serialized_end=300
  _globals['_SYSTEMMODECHANGENOTIFICATION']._serialized_start=302
  _globals['_SYSTEMMODECHANGENOTIFICATION']._serialized_end=427
# @@protoc_insertion_point(module_scope)
