# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/task_actions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/task_actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.common import file_pb2 as truffle_dot_common_dot_file__pb2
from truffle.os import task_pb2 as truffle_dot_os_dot_task__pb2
try:
  truffle_dot_os_dot_task__info__pb2 = truffle_dot_os_dot_task__pb2.truffle_dot_os_dot_task__info__pb2
except AttributeError:
  truffle_dot_os_dot_task__info__pb2 = truffle_dot_os_dot_task__pb2.truffle.os.task_info_pb2
try:
  truffle_dot_os_dot_task__user__response__pb2 = truffle_dot_os_dot_task__pb2.truffle_dot_os_dot_task__user__response__pb2
except AttributeError:
  truffle_dot_os_dot_task__user__response__pb2 = truffle_dot_os_dot_task__pb2.truffle.os.task_user_response_pb2
try:
  truffle_dot_os_dot_task__step__pb2 = truffle_dot_os_dot_task__pb2.truffle_dot_os_dot_task__step__pb2
except AttributeError:
  truffle_dot_os_dot_task__step__pb2 = truffle_dot_os_dot_task__pb2.truffle.os.task_step_pb2
try:
  truffle_dot_common_dot_content__pb2 = truffle_dot_os_dot_task__pb2.truffle_dot_common_dot_content__pb2
except AttributeError:
  truffle_dot_common_dot_content__pb2 = truffle_dot_os_dot_task__pb2.truffle.common.content_pb2
from truffle.os import task_target_pb2 as truffle_dot_os_dot_task__target__pb2
from truffle.os import task_options_pb2 as truffle_dot_os_dot_task__options__pb2
from truffle.os import task_user_response_pb2 as truffle_dot_os_dot_task__user__response__pb2
from truffle.common import tool_provider_pb2 as truffle_dot_common_dot_tool__provider__pb2

from truffle.os.task_pb2 import *
from truffle.os.task_target_pb2 import *
from truffle.os.task_options_pb2 import *
from truffle.os.task_user_response_pb2 import *
from truffle.common.tool_provider_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/os/task_actions.proto\x12\ntruffle.os\x1a\x19truffle/common/file.proto\x1a\x15truffle/os/task.proto\x1a\x1ctruffle/os/task_target.proto\x1a\x1dtruffle/os/task_options.proto\x1a#truffle/os/task_user_response.proto\x1a\"truffle/common/tool_provider.proto\">\n\x14InterruptTaskRequest\x12&\n\x06target\x18\x01 \x01(\x0b\x32\x16.truffle.os.TargetTask\"`\n\x07NewTask\x12-\n\x0cuser_message\x18\x01 \x01(\x0b\x32\x17.truffle.os.UserMessage\x12\x11\n\tapp_uuids\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65\x66\x65r_start\x18\x03 \x01(\x08\"\xf7\x01\n\x0fOpenTaskRequest\x12/\n\rexisting_task\x18\x01 \x01(\x0b\x32\x16.truffle.os.TargetTaskH\x00\x12\'\n\x08new_task\x18\x02 \x01(\x0b\x32\x13.truffle.os.NewTaskH\x00\x12-\n\x07options\x18\x03 \x01(\x0b\x32\x17.truffle.os.TaskOptionsH\x01\x88\x01\x01\x12\x45\n\x17\x65xternal_tool_providers\x18\x04 \x03(\x0b\x32$.truffle.common.ExternalToolProviderB\x08\n\x06targetB\n\n\x08_options\"\x88\x01\n\x1bTaskSetAvailableAppsRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tapp_uuids\x18\x02 \x03(\t\x12\x45\n\x17\x65xternal_tool_providers\x18\x03 \x03(\x0b\x32$.truffle.common.ExternalToolProvider\"\x1e\n\x1cTaskSetAvailableAppsResponse\"\x14\n\x12TaskActionResponse\"k\n#TaskTestExternalToolProviderRequest\x12\x44\n\x16\x65xternal_tool_provider\x18\x01 \x01(\x0b\x32$.truffle.common.ExternalToolProvider\"e\n$TaskTestExternalToolProviderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1a\n\rerror_message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_message\"6\n\x11TaskRenameRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\"7\n\x12TaskRenameResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\"$\n\x11TaskDeleteRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x14\n\x12TaskDeleteResponseP\x01P\x02P\x03P\x04P\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.task_actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERRUPTTASKREQUEST']._serialized_start=229
  _globals['_INTERRUPTTASKREQUEST']._serialized_end=291
  _globals['_NEWTASK']._serialized_start=293
  _globals['_NEWTASK']._serialized_end=389
  _globals['_OPENTASKREQUEST']._serialized_start=392
  _globals['_OPENTASKREQUEST']._serialized_end=639
  _globals['_TASKSETAVAILABLEAPPSREQUEST']._serialized_start=642
  _globals['_TASKSETAVAILABLEAPPSREQUEST']._serialized_end=778
  _globals['_TASKSETAVAILABLEAPPSRESPONSE']._serialized_start=780
  _globals['_TASKSETAVAILABLEAPPSRESPONSE']._serialized_end=810
  _globals['_TASKACTIONRESPONSE']._serialized_start=812
  _globals['_TASKACTIONRESPONSE']._serialized_end=832
  _globals['_TASKTESTEXTERNALTOOLPROVIDERREQUEST']._serialized_start=834
  _globals['_TASKTESTEXTERNALTOOLPROVIDERREQUEST']._serialized_end=941
  _globals['_TASKTESTEXTERNALTOOLPROVIDERRESPONSE']._serialized_start=943
  _globals['_TASKTESTEXTERNALTOOLPROVIDERRESPONSE']._serialized_end=1044
  _globals['_TASKRENAMEREQUEST']._serialized_start=1046
  _globals['_TASKRENAMEREQUEST']._serialized_end=1100
  _globals['_TASKRENAMERESPONSE']._serialized_start=1102
  _globals['_TASKRENAMERESPONSE']._serialized_end=1157
  _globals['_TASKDELETEREQUEST']._serialized_start=1159
  _globals['_TASKDELETEREQUEST']._serialized_end=1195
  _globals['_TASKDELETERESPONSE']._serialized_start=1197
  _globals['_TASKDELETERESPONSE']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
