# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/task_user_response.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/task_user_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.os import task_target_pb2 as truffle_dot_os_dot_task__target__pb2
from truffle.common import file_pb2 as truffle_dot_common_dot_file__pb2
from truffle.common import content_pb2 as truffle_dot_common_dot_content__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#truffle/os/task_user_response.proto\x12\ntruffle.os\x1a\x1ctruffle/os/task_target.proto\x1a\x19truffle/common/file.proto\x1a\x1ctruffle/common/content.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x0bUserMessage\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x1f\n\x17\x61ttached_feed_entry_ids\x18\x02 \x03(\x04\x12\x36\n\x0f\x61ttached_images\x18\x03 \x03(\x0b\x32\x1d.truffle.common.AttachedImage\"7\n\x13PendingUserResponse\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\r\"\x9e\x01\n\x14RespondToTaskRequest\x12\r\n\x05steer\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\r\x12(\n\x07message\x18\x04 \x01(\x0b\x32\x17.truffle.os.UserMessage\x12+\n\x05\x66iles\x18\x05 \x03(\x0b\x32\x1c.truffle.common.AttachedFile\"k\n\x1eUpdateUserResponseQueueRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x38\n\x10queued_responses\x18\x02 \x03(\x0b\x32\x1e.truffle.os.QueuedUserResponse\"\xa8\x01\n\x12QueuedUserResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12(\n\x07message\x18\x02 \x01(\x0b\x32\x17.truffle.os.UserMessage\x12-\n\tqueued_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x05\x66iles\x18\x05 \x03(\x0b\x32\x1c.truffle.common.AttachedFileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.task_user_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=171
  _globals['_USERMESSAGE']._serialized_end=290
  _globals['_PENDINGUSERRESPONSE']._serialized_start=292
  _globals['_PENDINGUSERRESPONSE']._serialized_end=347
  _globals['_RESPONDTOTASKREQUEST']._serialized_start=350
  _globals['_RESPONDTOTASKREQUEST']._serialized_end=508
  _globals['_UPDATEUSERRESPONSEQUEUEREQUEST']._serialized_start=510
  _globals['_UPDATEUSERRESPONSEQUEUEREQUEST']._serialized_end=617
  _globals['_QUEUEDUSERRESPONSE']._serialized_start=620
  _globals['_QUEUEDUSERRESPONSE']._serialized_end=788
# @@protoc_insertion_point(module_scope)
