# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/tool_queries.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/os/tool_queries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/os/tool_queries.proto\x12\ntruffle.os\"\xab\x01\n\nToolRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x19\n\x0cicon_dataurl\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x08\x61pp_uuid\x18\x07 \x01(\tH\x00\x12\x13\n\tnamespace\x18\x08 \x01(\tH\x00\x42\n\n\x08providerB\x0f\n\r_icon_dataurl\"8\n\x13ToolsGetToolRequest\x12\x0f\n\x07tool_id\x18\x01 \x01(\t\x12\x10\n\x08no_icons\x18\x02 \x01(\x08\"+\n\x17ToolsGetAllToolsRequest\x12\x10\n\x08no_icons\x18\x01 \x01(\x08\"@\n\x1aToolsGetToolsForAppRequest\x12\x10\n\x08\x61pp_uuid\x18\x01 \x01(\t\x12\x10\n\x08no_icons\x18\x02 \x01(\x08\"7\n\x0eToolRecordList\x12%\n\x05tools\x18\x01 \x03(\x0b\x32\x16.truffle.os.ToolRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.tool_queries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLRECORD']._serialized_start=46
  _globals['_TOOLRECORD']._serialized_end=217
  _globals['_TOOLSGETTOOLREQUEST']._serialized_start=219
  _globals['_TOOLSGETTOOLREQUEST']._serialized_end=275
  _globals['_TOOLSGETALLTOOLSREQUEST']._serialized_start=277
  _globals['_TOOLSGETALLTOOLSREQUEST']._serialized_end=320
  _globals['_TOOLSGETTOOLSFORAPPREQUEST']._serialized_start=322
  _globals['_TOOLSGETTOOLSFORAPPREQUEST']._serialized_end=386
  _globals['_TOOLRECORDLIST']._serialized_start=388
  _globals['_TOOLRECORDLIST']._serialized_end=443
# @@protoc_insertion_point(module_scope)
