# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/app/app_install.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/app/app_install.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.os import installer_pb2 as truffle_dot_os_dot_installer__pb2
try:
  truffle_dot_app_dot_app__pb2 = truffle_dot_os_dot_installer__pb2.truffle_dot_app_dot_app__pb2
except AttributeError:
  truffle_dot_app_dot_app__pb2 = truffle_dot_os_dot_installer__pb2.truffle.app.app_pb2
from truffle.app import app_build_pb2 as truffle_dot_app_dot_app__build__pb2
from truffle.app import background_pb2 as truffle_dot_app_dot_background__pb2
from truffle.app import foreground_pb2 as truffle_dot_app_dot_foreground__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/app/app_install.proto\x12\x0btruffle.app\x1a\x1atruffle/os/installer.proto\x1a\x1btruffle/app/app_build.proto\x1a\x1ctruffle/app/background.proto\x1a\x1ctruffle/app/foreground.proto\".\n\x1aGetFinalInstallInfoRequest\x12\x10\n\x08\x61pp_uuid\x18\x01 \x01(\t\"\xc3\x01\n\x1bGetFinalInstallInfoResponse\x12?\n\rbg_build_info\x18\x01 \x01(\x0b\x32#.truffle.app.BackgroundAppBuildInfoH\x00\x88\x01\x01\x12?\n\rfg_build_info\x18\x02 \x01(\x0b\x32#.truffle.app.ForegroundAppBuildInfoH\x01\x88\x01\x01\x42\x10\n\x0e_bg_build_infoB\x10\n\x0e_fg_build_info2\xce\x01\n\x11\x41ppInstallService\x12O\n\nInstallApp\x12\x1d.truffle.os.AppInstallRequest\x1a\x1e.truffle.os.AppInstallResponse(\x01\x30\x01\x12h\n\x13GetFinalInstallInfo\x12\'.truffle.app.GetFinalInstallInfoRequest\x1a(.truffle.app.GetFinalInstallInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.app.app_install_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFINALINSTALLINFOREQUEST']._serialized_start=163
  _globals['_GETFINALINSTALLINFOREQUEST']._serialized_end=209
  _globals['_GETFINALINSTALLINFORESPONSE']._serialized_start=212
  _globals['_GETFINALINSTALLINFORESPONSE']._serialized_end=407
  _globals['_APPINSTALLSERVICE']._serialized_start=410
  _globals['_APPINSTALLSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
