# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/app/app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/app/app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.common import icon_pb2 as truffle_dot_common_dot_icon__pb2
from truffle.app import foreground_pb2 as truffle_dot_app_dot_foreground__pb2
from truffle.app import background_pb2 as truffle_dot_app_dot_background__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15truffle/app/app.proto\x12\x0btruffle.app\x1a\x19truffle/common/icon.proto\x1a\x1ctruffle/app/foreground.proto\x1a\x1ctruffle/app/background.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x0b\x41ppMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04icon\x18\x02 \x01(\x0b\x32\x14.truffle.common.Icon\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tbundle_id\x18\x04 \x01(\t\"$\n\tAppConfig\x12\x17\n\x0f\x63\x61n_reconfigure\x18\x01 \x01(\x08\"\x8b\x03\n\x03\x41pp\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12*\n\x08metadata\x18\x02 \x01(\x0b\x32\x18.truffle.app.AppMetadata\x12\x33\n\nforeground\x18\x03 \x01(\x0b\x32\x1a.truffle.app.ForegroundAppH\x00\x88\x01\x01\x12\x33\n\nbackground\x18\x04 \x01(\x0b\x32\x1a.truffle.app.BackgroundAppH\x01\x88\x01\x01\x12)\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x15.truffle.app.AppErrorH\x02\x88\x01\x01\x12&\n\x06\x63onfig\x18\x06 \x01(\x0b\x32\x16.truffle.app.AppConfig\x12\x30\n\x0cinstalled_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0flast_updated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\r\n\x0b_foregroundB\r\n\x0b_backgroundB\x08\n\x06_error\"\xc1\x01\n\x08\x41ppError\x12\x33\n\nerror_type\x18\x01 \x01(\x0e\x32\x1f.truffle.app.AppError.ErrorType\x12\x15\n\rerror_message\x18\x02 \x01(\t\"i\n\tErrorType\x12\x1a\n\x16\x41PP_ERROR_TYPE_INVALID\x10\x00\x12\x15\n\x11\x41PP_ERROR_RUNTIME\x10\x01\x12\x12\n\x0e\x41PP_ERROR_AUTH\x10\x02\x12\x15\n\x11\x41PP_ERROR_UNKNOWN\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.app.app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPMETADATA']._serialized_start=158
  _globals['_APPMETADATA']._serialized_end=261
  _globals['_APPCONFIG']._serialized_start=263
  _globals['_APPCONFIG']._serialized_end=299
  _globals['_APP']._serialized_start=302
  _globals['_APP']._serialized_end=697
  _globals['_APPERROR']._serialized_start=700
  _globals['_APPERROR']._serialized_end=893
  _globals['_APPERROR_ERRORTYPE']._serialized_start=788
  _globals['_APPERROR_ERRORTYPE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
