# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/app/app_runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/app/app_runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.app import app_pb2 as truffle_dot_app_dot_app__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/app/app_runtime.proto\x12\x0btruffle.app\x1a\x15truffle/app/app.proto\"r\n\x1c\x41ppRuntimeReportErrorRequest\x12\x10\n\x08\x61pp_uuid\x18\x01 \x01(\t\x12$\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x15.truffle.app.AppError\x12\x1a\n\x12needs_intervention\x18\x03 \x01(\x08\"\x1f\n\x1d\x41ppRuntimeReportErrorResponse2y\n\x11\x41ppRuntimeService\x12\x64\n\x0bReportError\x12).truffle.app.AppRuntimeReportErrorRequest\x1a*.truffle.app.AppRuntimeReportErrorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.app.app_runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPRUNTIMEREPORTERRORREQUEST']._serialized_start=69
  _globals['_APPRUNTIMEREPORTERRORREQUEST']._serialized_end=183
  _globals['_APPRUNTIMEREPORTERRORRESPONSE']._serialized_start=185
  _globals['_APPRUNTIMEREPORTERRORRESPONSE']._serialized_end=216
  _globals['_APPRUNTIMESERVICE']._serialized_start=218
  _globals['_APPRUNTIMESERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
