# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from truffle.app import app_runtime_pb2 as truffle_dot_app_dot_app__runtime__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in truffle/app/app_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportError = channel.unary_unary(
                '/truffle.app.AppRuntimeService/ReportError',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorResponse.FromString,
                _registered_method=True)
        self.GetAppVar = channel.unary_unary(
                '/truffle.app.AppRuntimeService/GetAppVar',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarResponse.FromString,
                _registered_method=True)
        self.SetAppVar = channel.unary_unary(
                '/truffle.app.AppRuntimeService/SetAppVar',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarResponse.FromString,
                _registered_method=True)
        self.DeleteAppVar = channel.unary_unary(
                '/truffle.app.AppRuntimeService/DeleteAppVar',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarResponse.FromString,
                _registered_method=True)
        self.ListAppVars = channel.unary_unary(
                '/truffle.app.AppRuntimeService/ListAppVars',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsResponse.FromString,
                _registered_method=True)
        self.AcquireForegroundMcp = channel.unary_unary(
                '/truffle.app.AppRuntimeService/AcquireForegroundMcp',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpResponse.FromString,
                _registered_method=True)
        self.RefreshForegroundMcp = channel.unary_unary(
                '/truffle.app.AppRuntimeService/RefreshForegroundMcp',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpResponse.FromString,
                _registered_method=True)
        self.ReleaseForegroundMcp = channel.unary_unary(
                '/truffle.app.AppRuntimeService/ReleaseForegroundMcp',
                request_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpRequest.SerializeToString,
                response_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpResponse.FromString,
                _registered_method=True)


class AppRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAppVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAppVar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAppVars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireForegroundMcp(self, request, context):
        """foreground MCP access — allows background apps to call their own foreground tools.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshForegroundMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseForegroundMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportError': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportError,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorResponse.SerializeToString,
            ),
            'GetAppVar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppVar,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarResponse.SerializeToString,
            ),
            'SetAppVar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAppVar,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarResponse.SerializeToString,
            ),
            'DeleteAppVar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAppVar,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarResponse.SerializeToString,
            ),
            'ListAppVars': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAppVars,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsResponse.SerializeToString,
            ),
            'AcquireForegroundMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireForegroundMcp,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpResponse.SerializeToString,
            ),
            'RefreshForegroundMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshForegroundMcp,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpResponse.SerializeToString,
            ),
            'ReleaseForegroundMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseForegroundMcp,
                    request_deserializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpRequest.FromString,
                    response_serializer=truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'truffle.app.AppRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('truffle.app.AppRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/ReportError',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReportErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/GetAppVar',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeGetAppVarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAppVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/SetAppVar',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeSetAppVarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAppVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/DeleteAppVar',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeDeleteAppVarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAppVars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/ListAppVars',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeListAppVarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireForegroundMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/AcquireForegroundMcp',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeAcquireForegroundMcpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshForegroundMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/RefreshForegroundMcp',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeRefreshForegroundMcpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseForegroundMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/truffle.app.AppRuntimeService/ReleaseForegroundMcp',
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpRequest.SerializeToString,
            truffle_dot_app_dot_app__runtime__pb2.AppRuntimeReleaseForegroundMcpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
