# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/app/default_app_manifest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/app/default_app_manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.common import icon_pb2 as truffle_dot_common_dot_icon__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from truffle.app import app_pb2 as truffle_dot_app_dot_app__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&truffle/app/default_app_manifest.proto\x12\x0btruffle.app\x1a\x19truffle/common/icon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15truffle/app/app.proto\"\xbd\x02\n\x12\x44\x65\x66\x61ultAppManifest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x38\n\x04\x61pps\x18\x03 \x03(\x0b\x32*.truffle.app.DefaultAppManifest.DefaultApp\x1a\xa9\x01\n\nDefaultApp\x12\r\n\x05index\x18\x01 \x01(\r\x12\x12\n\nbundle_url\x18\x02 \x01(\t\x12*\n\x08metadata\x18\x03 \x01(\x0b\x32\x18.truffle.app.AppMetadata\x12\x12\n\nbundle_md5\x18\x04 \x01(\t\x12\x1b\n\x13provides_foreground\x18\x05 \x01(\x08\x12\x1b\n\x13provides_background\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.app.default_app_manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEFAULTAPPMANIFEST']._serialized_start=139
  _globals['_DEFAULTAPPMANIFEST']._serialized_end=456
  _globals['_DEFAULTAPPMANIFEST_DEFAULTAPP']._serialized_start=287
  _globals['_DEFAULTAPPMANIFEST_DEFAULTAPP']._serialized_end=456
# @@protoc_insertion_point(module_scope)
