# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/app/foreground.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'truffle/app/foreground.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.app import app_build_pb2 as truffle_dot_app_dot_app__build__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/app/foreground.proto\x12\x0btruffle.app\x1a\x1btruffle/app/app_build.proto\"\xa5\x01\n\rForegroundApp\x12\x41\n\x0f\x61vailable_tools\x18\x01 \x03(\x0b\x32(.truffle.app.ForegroundApp.AvailableTool\x1aQ\n\rAvailableTool\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x18\n\x10tool_description\x18\x02 \x01(\t\x12\x13\n\x0b\x61rgs_schema\x18\x03 \x01(\t\"E\n\x16\x46oregroundAppBuildInfo\x12+\n\x07process\x18\x01 \x01(\x0b\x32\x1a.truffle.app.ProcessConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.app.foreground_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOREGROUNDAPP']._serialized_start=75
  _globals['_FOREGROUNDAPP']._serialized_end=240
  _globals['_FOREGROUNDAPP_AVAILABLETOOL']._serialized_start=159
  _globals['_FOREGROUNDAPP_AVAILABLETOOL']._serialized_end=240
  _globals['_FOREGROUNDAPPBUILDINFO']._serialized_start=242
  _globals['_FOREGROUNDAPPBUILDINFO']._serialized_end=311
# @@protoc_insertion_point(module_scope)
